class Question {
  final int id, answer;
  final String question;
  final List<String> options;

  Question({this.id, this.question, this.answer, this.options});
}

const List sample_data = [
  {
    "id": 1,
    "question": "What is the Arabic word for 'book'?",
    "options": ["كتاب", "House", "Car", "Pencil"],
    "answer_index": 0,
  },
  {
    "id": 2,
    "question": "What is the English word for 'مدرسة'?",
    "options": ["School", "Tree", "Chair", "Shoes"],
    "answer_index": 0,
  },
  {
    "id": 3,
    "question": "What is the Arabic translation for 'cat'?",
    "options": ["قطة", "Apple", "Table", "Bicycle"],
    "answer_index": 0,
  },
  {
    "id": 4,
    "question": "What is the English translation for 'شمس'?",
    "options": ["Sun", "Book", "Dog", "Hat"],
    "answer_index": 0,
  },
  {
    "id": 5,
    "question": "What is the Arabic word for 'water'?",
    "options": ["ماء", "Ball", "Chair", "Fish"],
    "answer_index": 0,
  },
  {
    "id": 6,
    "question": "What is the English word for 'وردة'?",
    "options": ["Rose", "Car", "Shirt", "Table"],
    "answer_index": 0,
  },
  {
    "id": 7,
    "question": "What is the Arabic translation for 'computer'?",
    "options": ["حاسوب", "Chair", "Dog", "Orange"],
    "answer_index": 0,
  },
  {
    "id": 8,
    "question": "What is the English translation for 'باب'?",
    "options": ["Door", "Cat", "Bird", "Ball"],
    "answer_index": 0,
  },
  {
    "id": 9,
    "question": "What is the Arabic word for 'friend'?",
    "options": ["صديق", "Sun", "Book", "Pencil"],
    "answer_index": 0,
  },
  {
    "id": 10,
    "question": "What is the English word for 'سيارة'?",
    "options": ["Car", "Fish", "Chair", "Dog"],
    "answer_index": 0,
  },
  {
    "id": 11,
    "question": "What is the Arabic translation for 'table'?",
    "options": ["طاولة", "Rose", "Book", "Bird"],
    "answer_index": 0,
  },
  {
    "id": 12,
    "question": "What is the English translation for 'شجرة'?",
    "options": ["Tree", "Cat", "Ball", "Sun"],
    "answer_index": 0,
  },
  {
    "id": 13,
    "question": "What is the Arabic word for 'apple'?",
    "options": ["تفاحة", "Car", "Table", "Sun"],
    "answer_index": 0,
  },
  {
    "id": 14,
    "question": "What is the English word for 'بيت'?",
    "options": ["House", "Fish", "Bird", "Dog"],
    "answer_index": 0,
  },
  {
    "id": 15,
    "question": "What is the Arabic word for 'shoes'?",
    "options": ["أحذية", "Book", "Table", "Sun"],
    "answer_index": 0,
  },
  {
    "id": 16,
    "question": "What is the English word for 'قلم'?",
    "options": ["Pencil", "Car", "Chair", "Ball"],
    "answer_index": 0,
  },
  {
    "id": 17,
    "question": "What is the Arabic translation for 'dog'?",
    "options": ["كلب", "Sun", "Book", "Table"],
    "answer_index": 0,
  },
  {
    "id": 18,
    "question": "What is the English translation for 'شمس'?",
    "options": ["Sun", "Fish", "Bird", "Cat"],
    "answer_index": 0,
  },
  {
    "id": 19,
    "question": "What is the Arabic word for 'ball'?",
    "options": ["كرة", "Car", "Chair", "Sun"],
    "answer_index": 0,
  },
  {
    "id": 20,
    "question": "What is the English word for 'سمك'?",
    "options": ["Fish", "House", "Table", "Pencil"],
    "answer_index": 0,
  },
  {
    "id": 21,
    "question": "What is the Arabic translation for 'happy'?",
    "options": ["سعيد", "Sad", "Excited", "Content"],
    "answer_index": 0,
  },
  {
    "id": 22,
    "question": "What is the English word for 'ساعة'?",
    "options": ["Clock", "Shirt", "Table", "Chair"],
    "answer_index": 0,
  },
  {
    "id": 23,
    "question": "What is the Arabic word for 'blue'?",
    "options": ["أزرق", "Green", "Red", "Yellow"],
    "answer_index": 0,
  },
  {
    "id": 24,
    "question": "What is the English translation for 'مدينة'?",
    "options": ["City", "Book", "Tree", "Sun"],
    "answer_index": 0,
  },
  {
    "id": 25,
    "question": "What is the Arabic word for 'teacher'?",
    "options": ["معلم", "Dog", "Cat", "Bird"],
    "answer_index": 0,
  },
  {
    "id": 26,
    "question": "What is the English word for 'فستان'?",
    "options": ["Dress", "Car", "Ball", "Fish"],
    "answer_index": 0,
  },
  {
    "id": 27,
    "question": "What is the Arabic translation for 'house'?",
    "options": ["منزل", "Sun", "Chair", "Pencil"],
    "answer_index": 0,
  },
  {
    "id": 28,
    "question": "What is the English translation for 'شمعة'?",
    "options": ["Candle", "Dog", "Table", "City"],
    "answer_index": 0,
  },
  {
    "id": 29,
    "question": "What is the Arabic word for 'banana'?",
    "options": ["موز", "Fish", "Shoes", "Car"],
    "answer_index": 0,
  },
  {
    "id": 30,
    "question": "What is the English word for 'سماء'?",
    "options": ["Sky", "Book", "Chair", "Clock"],
    "answer_index": 0,
  },
  {
    "id": 31,
    "question": "What is the Arabic word for 'family'?",
    "options": ["عائلة", "Sun", "Table", "Fish"],
    "answer_index": 0,
  },
  {
    "id": 32,
    "question": "What is the English word for 'ثلج'?",
    "options": ["Snow", "Car", "Dog", "Ball"],
    "answer_index": 0,
  },
  {
    "id": 33,
    "question": "What is the Arabic translation for 'school'?",
    "options": ["مدرسة", "Tree", "City", "Dress"],
    "answer_index": 0,
  },
  {
    "id": 34,
    "question": "What is the English translation for 'جدار'?",
    "options": ["Wall", "Fish", "Sky", "Candle"],
    "answer_index": 0,
  },
  {
    "id": 35,
    "question": "What is the Arabic word for 'cat'?",
    "options": ["قطة", "Sun", "Car", "City"],
    "answer_index": 0,
  },
  {
    "id": 36,
    "question": "What is the English word for 'تفاح'?",
    "options": ["Apple", "Clock", "Dress", "Table"],
    "answer_index": 0,
  },
  {
    "id": 37,
    "question": "What is the Arabic word for 'bread'?",
    "options": ["خبز", "Chair", "Sky", "Snow"],
    "answer_index": 0,
  },
  {
    "id": 38,
    "question": "What is the English word for 'حقيبة'?",
    "options": ["Bag", "Fish", "Candle", "City"],
    "answer_index": 0,
  },
  {
    "id": 39,
    "question": "What is the Arabic translation for 'mountain'?",
    "options": ["جبل", "Car", "Table", "Sky"],
    "answer_index": 0,
  },
  {
    "id": 40,
    "question": "What is the English translation for 'بحر'?",
    "options": ["Sea", "City", "Candle", "Clock"],
    "answer_index": 0,
  },
  {
    "id": 41,
    "question": "What is the Arabic word for 'mother'?",
    "options": ["أم", "Dog", "Book", "Dress"],
    "answer_index": 0,
  },
  {
    "id": 42,
    "question": "What is the English word for 'أخ'?",
    "options": ["Brother", "Fish", "Wall", "Apple"],
    "answer_index": 0,
  },
  {
    "id": 43,
    "question": "What is the Arabic word for 'flower'?",
    "options": ["زهرة", "Table", "City", "Sky"],
    "answer_index": 0,
  },
  {
    "id": 44,
    "question": "What is the English word for 'شمس'?",
    "options": ["Sun", "Candle", "Snow", "Car"],
    "answer_index": 0,
  },
  {
    "id": 45,
    "question": "What is the Arabic translation for 'tree'?",
    "options": ["شجرة", "Clock", "Bag", "Brother"],
    "answer_index": 0,
  },
  {
    "id": 46,
    "question": "What is the English translation for 'كتاب'?",
    "options": ["Book", "Chair", "Sky", "Dress"],
    "answer_index": 0,
  },
  {
    "id": 47,
    "question": "What is the Arabic word for 'fish'?",
    "options": ["سمك", "Sun", "Sea", "Bag"],
    "answer_index": 0,
  },
  {
    "id": 48,
    "question": "What is the English word for 'بيت'?",
    "options": ["House", "Clock", "Snow", "Apple"],
    "answer_index": 0,
  },
  {
    "id": 49,
    "question": "What is the Arabic word for 'car'?",
    "options": ["سيارة", "City", "Dress", "Table"],
    "answer_index": 0,
  },
  {
    "id": 50,
    "question": "What is the English word for 'شهر'?",
    "options": ["Month", "Bag", "Fish", "Candle"],
    "answer_index": 0,
  },
];
