class Question {
  final int id, answer;
  final String question;
  final List<String> options;

  Question({this.id, this.question, this.answer, this.options});
}

const List sample_data = [
  {
    "id": 1,
    "question": "What is the Amharic translation for 'hello'?",
    "options": ["ሰላም (Selam)", "Goodbye", "Thank you", "Yes"],
    "answer_index": 0,
  },
  {
    "id": 2,
    "question": "What is the English word for 'በዓል'?",
    "options": ["celabrate", "Car", "Book", "Chair"],
    "answer_index": 0,
  },
  {
    "id": 3,
    "question": "What is the Amharic word for 'water'?",
    "options": ["ውሃ (Wuha)", "Fire", "Food", "Sky"],
    "answer_index": 0,
  },
  {
    "id": 4,
    "question": "What is the English translation for 'አስር'?",
    "options": ["ten", "Sun", "Tree", "Fish"],
    "answer_index": 0,
  },
  {
    "id": 5,
    "question": "What is the Amharic word for 'food'?",
    "options": ["ምግብ (Migib)", "Table", "City", "Chair"],
    "answer_index": 0,
  },
  {
    "id": 6,
    "question": "What is the English word for 'እናት'?",
    "options": ["mother", "Car", "Ball", "Fish"],
    "answer_index": 0,
  },
  {
    "id": 7,
    "question": "What is the Amharic translation for 'wusha'?",
    "options": ["እናት (Enat)", "Dog", "Cat", "Bird"],
    "answer_index": 1,
  },
  {
    "id": 8,
    "question": "What is the English translation for 'ketama'?",
    "options": ["Mother", "Fish", "Table", "City"],
    "answer_index": 3,
  },
  {
    "id": 9,
    "question": "What is the Amharic word for 'bird'?",
    "options": ["ወፍ (We)", "Sun", "Car", "City"],
    "answer_index": 0,
  },
  {
    "id": 10,
    "question": "What is the English word for 'sat'?",
    "options": ["time", "word", "Dress", "Table"],
    "answer_index": 0,
  },
  {
    "id": 11,
    "question": "What is the Amharic translation for 'book'?",
    "options": ["መፅሀፍ (Mets'haf)", "Sky", "Bag", "Brother"],
    "answer_index": 0,
  },
  {
    "id": 12,
    "question": "What is the English translation for 'makina'?",
    "options": ["Book", "Candle", "Snow", "Car"],
    "answer_index": 3,
  },
  {
    "id": 13,
    "question": "What is the Amharic word for 'father'?",
    "options": ["አባት (Abat)", "Sun", "Sea", "Bag"],
    "answer_index": 0,
  },
  {
    "id": 14,
    "question": "What is the English word for 'bet'?",
    "options": ["house", "Clock", "Snow", "Apple"],
    "answer_index": 0,
  },
  {
    "id": 15,
    "question": "What is the Amharic translation for 'tree'?",
    "options": ["zaf", "bet", "wuha", "Sky"],
    "answer_index": 0,
  },
  {
    "id": 16,
    "question": "What is the English translation for 'wuha'?",
    "options": ["water", "Chair", "eat", "morning"],
    "answer_index": 0,
  },
  {
    "id": 17,
    "question": "What is the Amharic word for 'fish'?",
    "options": ["wolaj", "asa", "Candle", "City"],
    "answer_index": 1,
  },
  {
    "id": 18,
    "question": "What is the English word for 'dimat'?",
    "options": ["Cat", "monkey", "walk", "night"],
    "answer_index": 0,
  },
  {
    "id": 19,
    "question": "What is the Amharic translation for 'light'?",
    "options": ["ብርሃን (Birhan)", "City", "Snow", "Clock"],
    "answer_index": 0,
  },
  {
    "id": 20,
    "question": "What is the English translation for 'monday'?",
    "options": ["ehud", "maksagno", "segno", "arb"],
    "answer_index": 2,
  },
  {
    "id": 21,
    "question": "What is the English translation for 'ልብ'?",
    "options": ["Night", "Rain", "Moon", "heart"],
    "answer_index": 3,
  },
  {
    "id": 22,
    "question": "What is the Amharic translation for 'tree'?",
    "options": ["አባት (Abat)", "City", "inchat", "Sky"],
    "answer_index": 2,
  },
  {
    "id": 23,
    "question": "What is the English word for 'ነጭ'?",
    "options": ["Small", "white", "Tall", "Short"],
    "answer_index": 1,
  },
  {
    "id": 24,
    "question": "What is the Amharic word for 'happy'?",
    "options": ["በዓል (Bela)", "Desta", "malqes", "Excited"],
    "answer_index": 1,
  },
  {
    "id": 25,
    "question": "What is the English translation for 'malqes'?",
    "options": ["Happy", "Cry", "Laugh", "Angry"],
    "answer_index": 1,
  },
  {
    "id": 26,
    "question": "What is the Amharic word for 'car'?",
    "options": ["መኪና (Mekina)", "House", "Book", "Table"],
    "answer_index": 0,
  },
  {
    "id": 27,
    "question": "What is the English word for 'afinca'?",
    "options": ["Ear", "Eye", "Nose", "Mouth"],
    "answer_index": 0,
  },
  {
    "id": 28,
    "question": "What is the Amharic translation for 'water'?",
    "options": ["ውሃ (Wuha)", "Fire", "Food", "Sky"],
    "answer_index": 0,
  },
  {
    "id": 29,
    "question": "What is the English translation for 'ayer'?",
    "options": ["Water", "Fire", "Earth", "Air"],
    "answer_index": 3,
  },
  {
    "id": 30,
    "question": "What is the Amharic word for 'brother'?",
    "options": ["ልዩ (Leyu)", "Enemy", "Stranger", "wandim"],
    "answer_index": 3,
  },
  {
    "id": 31,
    "question": "What is the English word for 'አይነት'?",
    "options": ["Type", "Kind", "Sort", "Shape"],
    "answer_index": 0,
  },
  {
    "id": 32,
    "question": "What is the Amharic translation for 'red'?",
    "options": ["ቀይ (K'ey)", "Blue", "Green", "Yellow"],
    "answer_index": 0,
  },
  {
    "id": 33,
    "question": "What is the English translation for 'bica'?",
    "options": ["Red", "Blue", "Green", "Yellow"],
    "answer_index": 3,
  },
  {
    "id": 34,
    "question": "What is the Amharic word for 'goodbye'?",
    "options": ["ደስታዪ (Desta'yu)", "dena hun", "Thank you", "Yes"],
    "answer_index": 1,
  },
  {
    "id": 35,
    "question": "What is the English word for 'amesaginalew'?",
    "options": ["Hello", "Goodbye", "Thank you", "Yes"],
    "answer_index": 2,
  },
  {
    "id": 36,
    "question": "What is the Amharic translation for 'kokeb'?",
    "options": ["ምድር (Midir)", "Sun", "Star", "Sky"],
    "answer_index": 2,
  },
  {
    "id": 37,
    "question": "What is the English translation for 'lij'?",
    "options": ["Moon", "chlid", "Star", "Sky"],
    "answer_index": 1,
  },
  {
    "id": 38,
    "question": "What is the Amharic word for 'food'?",
    "options": ["ምግብ (Migib)", "Table", "City", "Chair"],
    "answer_index": 0,
  },
  {
    "id": 39,
    "question": "What is the English word for 'mata'?",
    "options": ["night", "day", "Plate", "tomorrow"],
    "answer_index": 0,
  },
  {
    "id": 40,
    "question": "What is the Amharic translation for 'tomorrow'?",
    "options": ["ወይ (Wey)", "nage", "Earth", "Air"],
    "answer_index": 1,
  },
  {
    "id": 41,
    "question": "What is the Amharic word for 'house'?",
    "options": ["ቤት (Bet)", "Car", "Book", "Table"],
    "answer_index": 0,
  },
  {
    "id": 42,
    "question": "What is the English translation for 'month'?",
    "options": ["House", "Car", "samint", "war"],
    "answer_index": 3,
  },
  {
    "id": 43,
    "question": "What is the Amharic translation for 'potato'?",
    "options": ["ድንች (Dinch)", "Dog", "Bird", "Fish"],
    "answer_index": 0,
  },
  {
    "id": 44,
    "question": "What is the English word for 'zare'?",
    "options": ["ten", "tomorrow", "yestarday", "today"],
    "answer_index": 3,
  },
  {
    "id": 45,
    "question": "What is the Amharic word for 'paper'?",
    "options": ["መጽሐፍ (Mets'haf)", "Pen", "waraqat", "Pencil"],
    "answer_index": 3,
  },
  {
    "id": 46,
    "question": "What is the English translation for 'wand'?",
    "options": ["he", "she", "male", "female"],
    "answer_index": 2,
  },
  {
    "id": 47,
    "question": "What is the Amharic translation for 'green'?",
    "options": ["አረንጓዴ (Aregagde)", "Red", "Blue", "Yellow"],
    "answer_index": 0,
  },
  {
    "id": 48,
    "question": "What is the English translation for 'set'?",
    "options": ["he", "she", "male", "female"],
    "answer_index": 3,
  },
  {
    "id": 49,
    "question": "What is the Amharic word for 'student'?",
    "options": ["ተማሪ (Temari)", "astamari", "timhirt", "Class"],
    "answer_index": 0,
  },
  {
    "id": 50,
    "question": "What is the English word for 'timhirt bet'?",
    "options": ["Teacher", "Student", "School", "Class"],
    "answer_index": 2,
  },
];
