class Question {
  final int id, answer;
  final String question;
  final List<String> options;

  Question({this.id, this.question, this.answer, this.options});
}

const List sample_data = [
  {
    "id": 1,
    "question": "What is the past tense of 'run'?",
    "options": ["Running", "Ran", "Runned", "Runs"],
    "answer_index": 1,
  },
  {
    "id": 2,
    "question": "Which word is a conjunction?",
    "options": ["Apple", "But", "Jumping", "Quickly"],
    "answer_index": 1,
  },
  {
    "id": 3,
    "question": "What is the plural form of 'child'?",
    "options": ["Childs", "Children", "Childes", "Childies"],
    "answer_index": 1,
  },
  {
    "id": 4,
    "question": "Which of the following is an adverb?",
    "options": ["Jump", "Quickly", "Green", "Jumping"],
    "answer_index": 1,
  },
  {
    "id": 5,
    "question": "What is the opposite of 'happy'?",
    "options": ["Joyful", "Sad", "Excited", "Content"],
    "answer_index": 1,
  },
  {
    "id": 6,
    "question": "What is the present participle of 'sing'?",
    "options": ["Sang", "Sung", "Singing", "Sings"],
    "answer_index": 2,
  },
  {
    "id": 7,
    "question": "Which of the following is a pronoun?",
    "options": ["Run", "He", "Book", "Jump"],
    "answer_index": 1,
  },
  {
    "id": 8,
    "question": "What is the comparative form of 'good'?",
    "options": ["Gooder", "Best", "Better", "Goodest"],
    "answer_index": 2,
  },
  {
    "id": 9,
    "question": "What is the opposite of 'high'?",
    "options": ["Low", "Tall", "Height", "Higher"],
    "answer_index": 0,
  },
  {
    "id": 10,
    "question": "Which of the following is a preposition?",
    "options": ["Over", "Run", "Quick", "Table"],
    "answer_index": 0,
  },
  {
    "id": 11,
    "question": "What is the superlative form of 'fast'?",
    "options": ["Faster", "Fastest", "Fasting", "Faste"],
    "answer_index": 1,
  },
  {
    "id": 12,
    "question": "What is the comparative form of 'big'?",
    "options": ["Big", "Bigger", "Biggest", "Bigly"],
    "answer_index": 1,
  },
  {
    "id": 13,
    "question": "Which of the following is a conjunction?",
    "options": ["And", "Jump", "Quick", "Table"],
    "answer_index": 0,
  },
  {
    "id": 14,
    "question": "What is the plural form of 'goose'?",
    "options": ["Gooses", "Goos", "Geese", "Goosies"],
    "answer_index": 2,
  },
  {
    "id": 15,
    "question": "Which word is an adjective?",
    "options": ["Run", "He", "Quick", "Running"],
    "answer_index": 2,
  },
  {
    "id": 16,
    "question": "What is the past tense of 'sing'?",
    "options": ["Sang", "Sung", "Singed", "Sing"],
    "answer_index": 0,
  },
  {
    "id": 17,
    "question": "What is the plural form of 'man'?",
    "options": ["Mans", "Man", "Mens", "Men"],
    "answer_index": 3,
  },
  {
    "id": 18,
    "question": "What is the opposite of 'old'?",
    "options": ["Ancient", "Young", "Elder", "Oldest"],
    "answer_index": 1,
  },
  {
    "id": 19,
    "question": "Which of the following is an adverb?",
    "options": ["Book", "Jump", "Quickly", "Green"],
    "answer_index": 2,
  },
  {
    "id": 20,
    "question": "What is the past tense of 'swim'?",
    "options": ["Swum", "Swimming", "Swam", "Swims"],
    "answer_index": 2,
  },
  {
    "id": 21,
    "question": "What is the plural form of 'mouse'?",
    "options": ["Mouses", "Mouse", "Mice", "Mousies"],
    "answer_index": 2,
  },
  {
    "id": 22,
    "question": "Which word is an adverb?",
    "options": ["Run", "Quick", "Book", "Running"],
    "answer_index": 1,
  },
  {
    "id": 23,
    "question": "What is the past tense of 'eat'?",
    "options": ["Eaten", "Ate", "Eating", "Eats"],
    "answer_index": 1,
  },
  {
    "id": 24,
    "question": "What is the superlative form of 'happy'?",
    "options": ["Happy", "Happily", "Happiest", "Happier"],
    "answer_index": 2,
  },
  {
    "id": 25,
    "question": "What is the opposite of 'fast'?",
    "options": ["Quick", "Slow", "Faster", "Speedy"],
    "answer_index": 1,
  },
  {
    "id": 26,
    "question": "Which of the following is a preposition?",
    "options": ["Run", "Above", "Jump", "Table"],
    "answer_index": 1,
  },
  {
    "id": 27,
    "question": "What is the plural form of 'ox'?",
    "options": ["Oxes", "Oxen", "Ox", "Oxies"],
    "answer_index": 1,
  },
  {
    "id": 28,
    "question": "Which word is a pronoun?",
    "options": ["She", "He", "Quick", "Running"],
    "answer_index": 0,
  },
  {
    "id": 29,
    "question": "What is the comparative form of 'bad'?",
    "options": ["Badly", "Badder", "Baddest", "Worse"],
    "answer_index": 3,
  },
  {
    "id": 30,
    "question": "What is the past tense of 'drink'?",
    "options": ["Drink", "Drank", "Drunk", "Drinks"],
    "answer_index": 1,
  },
  {
    "id": 31,
    "question": "What is the plural form of 'wolf'?",
    "options": ["Wolfes", "Wolves", "Wolfs", "Wolfies"],
    "answer_index": 1,
  },
  {
    "id": 32,
    "question": "Which of the following is an adjective?",
    "options": ["Jump", "Quick", "Green", "Jumping"],
    "answer_index": 2,
  },
  {
    "id": 33,
    "question": "What is the opposite of 'hot'?",
    "options": ["Cold", "Warm", "Heat", "Hottest"],
    "answer_index": 0,
  },
  {
    "id": 34,
    "question": "What is the present participle of 'swim'?",
    "options": ["Swum", "Swimming", "Swam", "Swims"],
    "answer_index": 1,
  },
  {
    "id": 35,
    "question": "What is the plural form of 'goat'?",
    "options": ["Goats", "Goat", "Gotes", "Goaties"],
    "answer_index": 0,
  },
  {
    "id": 36,
    "question": "Which word is a conjunction?",
    "options": ["And", "Jump", "Quick", "Table"],
    "answer_index": 0,
  },
  {
    "id": 37,
    "question": "What is the superlative form of 'far'?",
    "options": ["Far", "Farest", "Furthest", "Further"],
    "answer_index": 2,
  },
  {
    "id": 38,
    "question": "What is the opposite of 'dark'?",
    "options": ["Light", "Shadow", "Black", "Darkest"],
    "answer_index": 0,
  },
  {
    "id": 39,
    "question": "Which of the following is an adverb?",
    "options": ["Book", "Jump", "Quickly", "Green"],
    "answer_index": 2,
  },
  {
    "id": 40,
    "question": "What is the past tense of 'write'?",
    "options": ["Written", "Wrote", "Writing", "Writes"],
    "answer_index": 1,
  },
  {
    "id": 41,
    "question": "What is the plural form of 'cactus'?",
    "options": ["Cactuses", "Cacti", "Cactus", "Cactues"],
    "answer_index": 1,
  },
  {
    "id": 42,
    "question": "Which word is a pronoun?",
    "options": ["It", "Quick", "She", "Running"],
    "answer_index": 0,
  },
  {
    "id": 43,
    "question": "What is the comparative form of 'high'?",
    "options": ["High", "Higher", "Highest", "Highly"],
    "answer_index": 1,
  },
  {
    "id": 44,
    "question": "What is the opposite of 'good'?",
    "options": ["Better", "Great", "Well", "Bad"],
    "answer_index": 3,
  },
  {
    "id": 45,
    "question": "What is the past tense of 'take'?",
    "options": ["Take", "Took", "Taken", "Taking"],
    "answer_index": 1,
  },
  {
    "id": 46,
    "question": "What is the plural form of 'knife'?",
    "options": ["Knifes", "Knives", "Knife", "Knive"],
    "answer_index": 1,
  },
  {
    "id": 47,
    "question": "Which of the following is a preposition?",
    "options": ["Book", "Jump", "Quick", "Under"],
    "answer_index": 3,
  },
  {
    "id": 48,
    "question": "What is the superlative form of 'strong'?",
    "options": ["Stronger", "Stronkest", "Strongest", "Strongly"],
    "answer_index": 2,
  },
  {
    "id": 49,
    "question": "What is the opposite of 'empty'?",
    "options": ["Full", "Hollow", "Void", "Emptiest"],
    "answer_index": 0,
  },
  {
    "id": 50,
    "question": "Which word is an adjective?",
    "options": ["Run", "He", "Quick", "Running"],
    "answer_index": 2,
  },
];
